### ISSUE TITLE
Subanta form of strīliṅga nouns

### ISSUE THREAD

**Issue by utkrssh** [sanskrit/padmini#1]
I am not able to generate desired subanta froms for strīliṅga nouns.
```python
from padmini.ashtadhyayi import subanta
from padmini.constants import Tag
print(subanta('bAlA', Tag.STRI, [ Tag.EKAVACANA, Tag.V1]).text)
```
The above program gives `bAlAH` as output. How to get `bAlA`?

**Comment by akprasad** [comment]
Thanks for letting me know. I'll follow up later this week.

**Comment by akprasad** [comment]
Apologies for the late follow-up. I have decided to deprecate this repo in favor of our new Rust implementation. See the README for updates on our port of this project to Rust.
